SELECT * FROM TABELA_DE_PRODUTOS;
-- TABELA DE PRODUTOS.SABOR, TABELA DE, PRODUTOS.PRECO DE LISTA,
-- TTENS NOTÃS FISCAIS.PRECO, ITENS NOTAS FISCAIS.QUANTIDADE
-- RELATORIO DE RANKTNG DE VENDA DE PRODUTOS POR SABOR POR ANO COLUNA DE PERCENTURL DO TOTAL
SELECT * FROM notas_fiscais;
SELECT * FROM ITENS_NOTAS_FISCAIS;


SELECT
    TBP.SABOR,
    EXTRACT(YEAR FROM NF.DATA_VENDA) AS ANO,
    SUM(ROUND (INF.PRECO * INF.QUANTIDADE, 1)) AS VALOR,
    ROUND((SUM(INF.PRECO * INF.QUANTIDADE, 1) / (SELECT SUM(PRECO * quantidade) FROM ITENS_NOTAS_FISCAIS)) * 100,2) AS PORCENTAGEM  
    
FROM TABELA_DE_PRODUTOS TBP

INNER JOIN ITENS_NOTAS_FISCAIS INF
    ON (TBP.CODIGO_DO_PRODUTO = INF.CODIGO_DO_PRODUTO)

INNER JOIN NOTAS_FISCAIS NF
    ON (NF.NUMERO = INF. NUMERO)

WHERE EXTRACT(YEAR FROM NF.DATA_VENDA) = 2016

GROUP BY TBP.SABOR, EXTRACT(YEAR FROM NF.DATA_VENDA)

ORDER BY SUM(INF.PRECO * INF.QUANTIDADE) DESC
;

SELECT SUM(PRECO * quantidade) FROM ITENS_NOTAS_FISCAIS AS TOTAL;




