SELECT 
    I.ITEM,
    I.DESCRIPTION,
    I.WEIGHT,
    I.WEIGHT_UM,
    IC.BUY_UM,
    DI.ITEM_CLAS_FISCL,
    DI.ITEM_IPI,
    NVL(SUM(SO.TOT_ORD_QTY - (SO.TOT_CANC_QTY + SO.TOT_SHIP_QTY)), 0) AS TOTAL_ENTREGUE
    
    
FROM ITEM I

    INNER JOIN D_ITEM DI ON (DI.ITEM = I.ITEM AND DI.REVISION = I.REVISION AND DI.CCN = 'SPL')
    INNER JOIN ITEM_CCN IC ON (I.ITEM = IC.ITEM AND I.REVISION = IC.REVISION)
    INNER JOIN SO ON (SO.ITEM = I.ITEM)

GROUP BY
    I.ITEM,
    I.DESCRIPTION,
    I.WEIGHT,
    I.WEIGHT_UM,
    IC.BUY_UM,
    DI.ITEM_CLAS_FISCL,
    DI.ITEM_IPI;
