SELECT FLOOR(SYSDATE - TO_DATE('26/09/2000', 'DD/MM/YYYY')) FROM DUAL;

SELECT * FROM notas_fiscais WHERE DATA_VENDA  = TO_DATE('2016', 'YYYY');

SELECT * FROM itens_notas_fiscais;

    SELECT DISTINCT
        INF.CODIGO_DO_PRODUTO,
        NF.IMPOSTO,
        NF.DATA_VENDA,
        --SUM(NF.IMPOSTO)
        TRUNC((SELECT SUM(IMPOSTO) FROM notas_fiscais WHERE DATA_VENDA  = TO_DATE('2016', 'YYYY'))) AS TOTAL

    FROM ITENS_NOTAS_FISCAIS INF

    INNER JOIN 
        NOTAS_FISCAIS NF ON (NF.NUMERO = INF.NUMERO)

    WHERE NF.DATA_VENDA  = TO_DATE('2016', 'YYYY');
    
    
    SELECT SUM(IMPOSTO) FROM notas_fiscais; -- WHERE DATA_VENDA  = TO_DATE('2016', 'YYYY')
    
    
    
    SELECT TO_CHAR(DATA_VENDA, 'YYYY'), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) 
    FROM NOTAS_FISCAIS NF
    INNER JOIN ITENS_NOTAS_FISCAIS INF ON NF.NUMERO = INF.NUMERO
    WHERE TO_CHAR(DATA_VENDA, 'YYYY') = 2016
    GROUP BY TO_CHAR(DATA_VENDA, 'YYYY');
    
    
    SELECT 
        'O cliente ' || TC.NOME || ', faturou ' ||
            SUM(INF.QUANTIDADE * PRECO) || ' no ano de ' || TO_CHAR(DATA_VENDA, 'YYYY') = '2016' AS FATURAMENTO
        
    FROM
    
        TABELA_DE_CLIENTES TC
        
        INNER JOIN NOTAS_FISCAIS NF ON (TC.CPF = NF.CPF)
        INNER JOIN ITENS_NOTAS_FISCAIS INF ON (INF.NUMERO = NF.NUMERO)
        WHERE TO_CHAR(DATA_VENDA, 'YYYY') = '2016'
        GROUP BY TC.CPF, TC.NOME
        ;


    SELECT * FROM NOTAS_FISCAIS;
    
    SELECT * FROM itens_notas_fiscais;